version: '3'

services:
  resume-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - PORT=8080
    restart: unless-stopped 