name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'GitHub User'
      environment:
        description: 'Deploy environment'
        required: true
        default: 'staging'

jobs:
  manual-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Hello, ${{ github.event.inputs.name }}!"
          echo "Deploying to ${{ github.event.inputs.environment }} environment."
